### ISSUE TITLE
Code issues (Memory leak is probable)

### ISSUE THREAD

**Issue by IllusionTheDev** [BGHDDevelopment/LuckPermsGUI#1]
I've analyzed the plugin's code and here are some tips to improve it:

Make multiple classes, as the Main class is full of junk:
- The main class listens to events on big method (InventoryClickEvent)
- The main class manages commands (You can make a class that implements CommandExecutor)

Some more issues:
- You are using a public static Map whose key is a Player (This will be pretty bad, since static variables can't be properly garbage collected, and storing player data using the Player class is pretty bad, you should use the UUID class and call Bukkit.getPlayer(uuid) when needed)

**Comment by BGHDDevelopment** [comment]
All the things noted were from the previous author, next few updates hopefully I will get to cleaning up the past code and improving the quality. I will leave this open and keep you updated!

**Comment by BGHDDevelopment** [comment]
I started work on this issue [ALPHA](https://github.com/BGHDDevelopment/LuckPermsGUI/commit/c35906c71a060e7fb8a7e09582ac0e7a0d7f9af7)

**Comment by BGHDDevelopment** [comment]
I have released the first update to fix the reported issues, I will close this for now and finish the update for calling the UUID next weekend.

Thanks for the report!
