### ISSUE TITLE
Hi, prefix setup problem

### ISSUE THREAD

**Issue by successed** [BGHDDevelopment/LuckPermsGUI#3]
Luckperm version : LuckPerms-Bukkit-5.0.72
Luckpermgui version: 3.4
server version 1.8.8 spigot

Group prefix change/remove/add not'a workt
![Screenshot_17](https://user-images.githubusercontent.com/13768414/74336536-81c4df00-4daf-11ea-80c3-8d9bb8dcbc1f.png)

**Comment by successed** [comment]
And i have set config.yml LuckPerms5 true, but not workt
![Screenshot_19](https://user-images.githubusercontent.com/13768414/74434261-20feda80-4e73-11ea-9607-91b0a719d594.png)

**Comment by BGHDDevelopment** [comment]
On the ToDo list and will be fixed soon

**Comment by BGHDDevelopment** [comment]
Fixed in [PullRequest](https://github.com/BGHDDevelopment/LuckPermsGUI/pull/4)

Releases tomorrow.
